- state: 'default'
  actions:
    - input: null
      command: 'Char'
      nextstate: null
    - input: ';'
      command: 'Semicolon'
      nextstate: null
    - input: "\n"
      command: 'Newline'
      nextstate: null
    - input: "\r"
      command: 'CarriageReturn'
      nextstate: null
    - input: '('
      command: 'OpenBracket'
      nextstate: null
    - input: ')'
      command: 'CloseBracket'
      nextstate: null
    - input: '{'
      command: 'OpenBrace'
      nextstate: null
    - input: '}'
      command: 'CloseBrace'
      nextstate: null
    - input: ' '
      command: 'Space'
      nextstate: 'spacing'
    - input: '/'
      command: 'AppendLexeme'
      nextstate: 'slash'
    - input: '*'
      command: 'AppendLexeme'
      nextstate: 'star'
    - input: '"'
      command: 'QuoteMark'
      nextstate: null
    - input: 'f'
      command: 'AppendLexeme'
      nextstate: 'f'
- state: 'spacing'
  actions:
    - input: ' '
      command: 'Spaces'
      nextstate: 'spacing'
    - input: null
      command: 'AppendPostpone'
      nextstate: null
- state: 'slash'
  actions:
    - input: '/'
      command: 'OneLineComment'
      nextstate: null
    - input: '*'
      command: 'OpenMultiLineComment'
      nextstate: null
    - input: null
      command: 'AppendPostpone'
      nextstate: null
- state: 'star'
  actions:
    - input: '/'
      command: 'CloseMultiLineComment'
      nextstate: null
    - input: null
      command: 'AppendPostpone'
      nextstate: null
- state: 'f'
  actions:
    - input: 'o'
      command: 'AppendLexeme'
      nextstate: 'fo'
    - input: null
      command: 'ReturnCharsAndAppendPostpone'
      nextstate: null
- state: 'fo'
  actions:
    - input: 'r'
      command: 'AppendLexeme'
      nextstate: 'for'
    - input: null
      command: 'ReturnCharsAndAppendPostpone'
      nextstate: null
- state: 'for'
  actions:
    - input: ' '
      command: 'For'
      nextstate: null
    - input: null
      command: 'ReturnCharsAndAppendPostpone'
      nextstate: null